/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.nilu.telas;

import java.sql.*;
import br.com.nilu.dal.ModuloConexao;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class TelaRelatorio extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public TelaRelatorio() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    private void total_OS() {
        String mes = cboMesOs.getSelectedItem().toString();
        if (mes.equals("Janeiro")) {
            mes = "01";
        } else if (mes.equals("Fevereiro")) {
            mes = "02";
        } else if (mes.equals("Março")) {
            mes = "03";
        } else if (mes.equals("Abril")) {
            mes = "04";
        } else if (mes.equals("Maio")) {
            mes = "05";
        } else if (mes.equals("Junho")) {
            mes = "06";
        } else if (mes.equals("Julho")) {
            mes = "07";
        } else if (mes.equals("Agosto")) {
            mes = "08";
        } else if (mes.equals("Setembro")) {
            mes = "09";
        } else if (mes.equals("Outubro")) {
            mes = "10";
        } else if (mes.equals("Novembro")) {
            mes = "11";
        } else {
            mes = "12";
        }

        String sql = "select count(os) from tbos where data_os like ?";
        String sql2 = "select count(os) from tbos where situacao = 'Entregue OK' ";
        int total_os = 0;
        int ativos;
        int passivos;

        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, cboAnoOs.getSelectedItem().toString() + "-" + mes + "%");
            rs = pst.executeQuery();
            if (rs.next()) {
                total_os = rs.getInt(1);
                lblTotOs.setText(Integer.toString(total_os));
            }

        } catch (Exception e) {
        }
        try {
            pst = conexao.prepareStatement(sql2);
            rs = pst.executeQuery();
            if (rs.next()) {
                ativos = rs.getInt(1);
                passivos = (total_os) - (ativos);
                lblAtivos.setText(Integer.toString(ativos));
                lblPassivos.setText(Integer.toString(passivos));

            }

        } catch (Exception e) {
        }
    }

    private void receita() {
        String sql = "select sum(total) from tbos where data_os like ?";
        String sql2 = "select sum(total) from tbos where situacao = 'Entregue OK' ";
        int totalCash = 0;
        int liquido;
        int aReceber;

        String mes = cboMesReceita.getSelectedItem().toString();
        if (mes.equals("Janeiro")) {
            mes = "01";
        } else if (mes.equals("Fevereiro")) {
            mes = "02";
        } else if (mes.equals("Março")) {
            mes = "03";
        } else if (mes.equals("Abril")) {
            mes = "04";
        } else if (mes.equals("Maio")) {
            mes = "05";
        } else if (mes.equals("Junho")) {
            mes = "06";
        } else if (mes.equals("Julho")) {
            mes = "07";
        } else if (mes.equals("Agosto")) {
            mes = "08";
        } else if (mes.equals("Setembro")) {
            mes = "09";
        } else if (mes.equals("Outubro")) {
            mes = "10";
        } else if (mes.equals("Novembro")) {
            mes = "11";
        } else {
            mes = "12";
        }
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, cboAnoReceita.getSelectedItem().toString() + "-" + mes + "%");
            rs = pst.executeQuery();
            if (rs.next()) {
                totalCash = rs.getInt(1);
                lblProjecao.setText("R$ "+Integer.toString(totalCash)+ ",00");
            }

        } catch (Exception e) {
        }
        try {
            pst = conexao.prepareStatement(sql2);
            rs = pst.executeQuery();
            if (rs.next()) {
                liquido = rs.getInt(1);
                aReceber = (totalCash) - (liquido);
                lblLiq.setText("R$ "+Integer.toString(liquido)+",00");
                lblAReceber.setText("R$ "+Integer.toString(aReceber)+",00");

            }

        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboMesOs = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboAnoOs = new javax.swing.JComboBox();
        btnPesqOs = new javax.swing.JButton();
        lblTotOs = new javax.swing.JLabel();
        lblAtivos = new javax.swing.JLabel();
        lblPassivos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cboMesReceita = new javax.swing.JComboBox();
        cboAnoReceita = new javax.swing.JComboBox();
        lblProjecao = new javax.swing.JLabel();
        lblLiq = new javax.swing.JLabel();
        lblAReceber = new javax.swing.JLabel();
        btnPesqReceita = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Relatórios");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordens de Serviços"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Total de OS.:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 51, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel2.setText("Pronto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 80, -1, -1));

        jLabel3.setText("Pendente:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 120, -1, -1));

        cboMesOs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jPanel1.add(cboMesOs, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel4.setText("Mês:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel5.setText("Ano:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        cboAnoOs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031" }));
        jPanel1.add(cboAnoOs, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 105, -1));

        btnPesqOs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/nilu/icons/miniLupa_search_48796.png"))); // NOI18N
        btnPesqOs.setText("Pesquisar");
        btnPesqOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqOsActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesqOs, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        lblTotOs.setText("null");
        jPanel1.add(lblTotOs, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 51, 59, -1));

        lblAtivos.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        lblAtivos.setText("null");
        jPanel1.add(lblAtivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 82, 59, -1));

        lblPassivos.setText("null");
        jPanel1.add(lblPassivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 120, 59, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 350, 240));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Receita"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Prev. Total:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 38, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel10.setText("Líquido:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 67, -1, -1));

        jLabel11.setText("à Receber:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 107, -1, -1));

        jLabel12.setText("Mês:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel13.setText("Ano:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        cboMesReceita.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fervereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jPanel2.add(cboMesReceita, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        cboAnoReceita.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031" }));
        jPanel2.add(cboAnoReceita, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 105, -1));

        lblProjecao.setText("null");
        jPanel2.add(lblProjecao, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 38, 150, -1));

        lblLiq.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        lblLiq.setText("null");
        jPanel2.add(lblLiq, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 69, 210, -1));

        lblAReceber.setText("null");
        jPanel2.add(lblAReceber, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 107, 160, -1));

        btnPesqReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/nilu/icons/miniLupa_search_48796.png"))); // NOI18N
        btnPesqReceita.setText("Pesquisar");
        btnPesqReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqReceitaActionPerformed(evt);
            }
        });
        jPanel2.add(btnPesqReceita, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 380, 230));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Fechamento"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 288, 750, -1));

        setBounds(0, 0, 802, 577);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesqOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqOsActionPerformed
        total_OS();
    }//GEN-LAST:event_btnPesqOsActionPerformed

    private void btnPesqReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqReceitaActionPerformed
        receita();
    }//GEN-LAST:event_btnPesqReceitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesqOs;
    private javax.swing.JButton btnPesqReceita;
    private javax.swing.JComboBox cboAnoOs;
    private javax.swing.JComboBox cboAnoReceita;
    private javax.swing.JComboBox cboMesOs;
    private javax.swing.JComboBox cboMesReceita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAReceber;
    private javax.swing.JLabel lblAtivos;
    private javax.swing.JLabel lblLiq;
    private javax.swing.JLabel lblPassivos;
    private javax.swing.JLabel lblProjecao;
    private javax.swing.JLabel lblTotOs;
    // End of variables declaration//GEN-END:variables
}
